config/routes.rb
Rails.application.routes.draw do

  root "restaurants#index"


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :restaurants do
    resources :reviews do
      resources :endorsements
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews,
        -> { extending WithUserAssociationExtension },
        dependent: :destroy

  validates :name, length: {minimum: 3}, uniqueness: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def belongs_to_user?(user)
    self.user == user
  end

  def average_rating
    return "N/A" if self.reviews == []
    self.reviews.inject(0) {|memo, review| memo + review.rating}/ (self.reviews.length)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }

  has_many :endorsements
  
  def belongs_to?(user)
    self.user == user
  end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
    attributes[:user] ||= user
    create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def new
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count }
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except =>[:index, :show]

  before_action :require_permission, :only => [:edit, :destroy]

  def require_permission
    if current_user != Restaurant.find(params[:id]).user
      flash[:notice] = 'You must have created this restaurant to do this'
      redirect_to root_path
    end
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    user = current_user if current_user
    if user
      @restaurant = user.restaurants.create(restaurant_params)
      redirect_to '/restaurants'
    else
      redirect_to '/new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :image)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    review = @restaurant.reviews.build_with_user(review_params, current_user)
    if review.save
      redirect_to '/restaurants'
    else
      if review.errors[:user]
        flash.next[:error] = review.errors[:user]
        redirect_to '/restaurants'
      else
        render :new
      end
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])

    unless @review.belongs_to?(current_user)
      flash.next[:error] = ["You cannot delete this review"]
      redirect_to '/restaurants'
    end

    @review.destroy
    flash[:notice] = 'Review deleted successfully'
    redirect_to '/restaurants'
  end

  private
  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>RailsYelp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <% end %>

    <div>YELP!!</div>

    <%= notice %>
    <% if flash[:error] %>
      <h3><%= flash[:error].join(" ") %></h3>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <%= image_tag restaurant.image.url(:thumb) %>
    <%if restaurant.average_rating == "N/A"%>
      <h3>Average rating: N/A %></h3>
    <%else%>
      <h3>Average rating: <%= "★" * restaurant.average_rating + "☆"* (5-restaurant.average_rating)%></h3>
    <%end%>
    <% if restaurant.belongs_to_user?(current_user)%>

    <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>

    <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>

    <%end%>
    <% if restaurant.reviews.any? %>
      <% restaurant.reviews.all.each { |review| %>
        Review: <%= review.thoughts %>
        Rating: <%= "★" * review.rating + "☆" * (5-review.rating)%>
        Number of endorsements: <span class='endorsements_count'> <%= review.endorsements.length %> </span>
        <%= link_to "Endorse Review", new_restaurant_review_endorsement_path(restaurant.id,review.id), class: 'endorsements-link' %>
        <% if review.belongs_to?(current_user) %>
        <%= link_to "Delete Your Review", restaurant_review_path(restaurant, review), method: :delete %>
        <% end %>
        <% } %>
    <% end %>
    <% unless current_user && current_user.has_reviewed?(restaurant) %>
      <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    <% end %>

  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<% if user_signed_in? %>
  <a href="/restaurants/new">Add a restaurant</a>
<% end %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors">
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %> </li>
      <% end %>
    </ul>
  </section>
<%end%>


<%= render "form" %>